GroupProjects/WebPage/Areas/Admin/Controllers/UsersController.cs
using GymSports.Data.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebPage.Areas.Admin.Controllers
{
    public class UsersController : Controller
    {
          private readonly ApplicationDbContext _context;

          public UsersController()
          {
               _context = new ApplicationDbContext();
          }

          public ActionResult Index()
          {
               var users = _context.Users
                   .Where(u => u.UserName != "manager" && u.UserName != "admin")
                   .ToList();

               return View(users);
          }

          [HttpPost]
          [ValidateAntiForgeryToken]
          public ActionResult Delete(string id)
          {
               var user = _context.Users.Find(id);
               if (user != null)
               {
                    _context.Users.Remove(user);
                    _context.SaveChanges();
               }

               return RedirectToAction("Index");
          }
     }
}

GroupProjects/WebPage/Controllers/GymsController.cs
using GymSports.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GymSports.Data.Filters;

namespace WebPage.Controllers
{
     [RedirectUnauthenticatedFilter]
     public class GymsController : Controller
    {
          private readonly GymsDbContext _dbContext;

          public GymsController()
          {
               _dbContext = new GymsDbContext();
          }
          public ActionResult Index()
          {
               List<GymPlace> places = _dbContext.GymPlaces.ToList();
               return View(places);
          }
          public ActionResult Details(int id)
          {
               GymPlace place = _dbContext.GymPlaces.Find(id);
               return View(place);
          }

          public ActionResult Create()
          {
               return View();
          }

          [HttpPost]
          public ActionResult Create(GymPlace gp)
          {
               _dbContext.GymPlaces.Add(gp);
               _dbContext.SaveChanges();
               return RedirectToAction("Index");
          }

          public ActionResult Delete(int? id)
          {
               var place = _dbContext.GymPlaces.Find(id);
               return View(place);
          }

          [HttpPost]
          public ActionResult Delete(int id)
          {
               var place = _dbContext.GymPlaces.Find(id);
               _dbContext.GymPlaces.Remove(place);
               _dbContext.SaveChanges();

               return RedirectToAction("Index");
          }
     }
}

GroupProjects/WebPage/Controllers/ProductsController.cs
using GymSports.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GymSports.Data.Filters;
using GymSports.Data.Identity;
using System.Data.Entity;

namespace WebPage.Controllers
{
     [RedirectUnauthenticatedFilter]
     public class ProductsController : Controller
     {
          private ProductsDbContext db = new ProductsDbContext();

          public ActionResult Index(string searchTerm = "")
          {
               List<GymProduct> products = db.GymProducts.Where(temp => temp.Name.Contains(searchTerm)).ToList();
               ViewBag.SearchTerm = searchTerm;
               return View(products);
          }

          public ActionResult Details(int id)
          {
               var product = db.GymProducts.Find(id);
               return View(product);
          }

          private Cart GetCartFromSession()
          {
               var cart = Session["Cart"] as Cart;

               if (cart == null)
               {
                    cart = db.Carts
                        .Include(c => c.CartItems)
                        .FirstOrDefault(c => c.UserID == User.Identity.Name);

                    if (cart == null)
                    {
                         cart = new Cart
                         {
                              CartID = Guid.NewGuid().ToString(),
                              UserID = User.Identity.Name,
                              CartItems = new List<CartItem>()
                         };

                         db.Carts.Add(cart);
                         db.SaveChanges();
                    }

                    SetCartToSession(cart);
               }

               return cart;
          }

          private void SetCartToSession(Cart cart)
          {
               Session["Cart"] = cart;
          }

          [HttpPost]
          public ActionResult AddToCart(int productId, int quantity)
          {
               var product = db.GymProducts.Find(productId);

               if (product != null)
               {
                    var cart = GetCartFromSession();

                    var existingCartItem = cart.CartItems.FirstOrDefault(item => item.ProductID == productId);

                    if (existingCartItem != null)
                    {
                         existingCartItem.Quantity += quantity;
                    }
                    else
                    {
                         var cartItem = new CartItem

                         {
                              ProductID = productId,
                              Quantity = quantity
                         };
                         cart.CartItems.Add(cartItem);
                    }

                    // Save the cart items to the database
                    db.SaveChanges();

                    SetCartToSession(cart);
               }

               return RedirectToAction("Cart");
          }

          public ActionResult Cart()
          {
               var cart = GetCartFromSession();
               Console.WriteLine(cart);
               return View(cart);
          }

          public ActionResult Checkout()
          {
               return View();
          }
     }
}

GroupProjects/WebPage/Areas/Admin/Views/Shared/_LayoutPageAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
     <meta charset="utf-8" />
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <title>SportsGym - Admin</title>
     @Styles.Render("~/Content/css")
     @Scripts.Render("~/bundles/modernizr")
     <!-- Bootstrap CSS -->
     <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css" rel="stylesheet">
     <!-- Font Awesome -->
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

     <style>
          body.dark-mode {
               background-color: #222;
               color: #fff;
          }

          .navbar-light .navbar-toggler-icon.text-light {
               background-image: url("data:image/svg+xml;charset=utf-8,%3Csvg viewBox='0 0 30 30' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='rgba(255,255,255,0.8)' stroke-linecap='round' stroke-miterlimit='10' stroke-width='2' d='M4 7h22M4 15h22M4 23h22'/%3E%3C/svg%3E");
          }

               .navbar-light .navbar-toggler-icon.text-light:focus,
               .navbar-light .navbar-toggler-icon.text-light:hover {
                    background-image: url("data:image/svg+xml;charset=utf-8,%3Csvg viewBox='0 0 30 30' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='rgba(255,255,255,1)' stroke-linecap='round' stroke-miterlimit='10' stroke-width='2' d='M4 7h22M4 15h22M4 23h22'/%3E%3C/svg%3E");
               }
     </style>
</head>
<body class="dark-mode">
     <nav class="navbar navbar-expand-sm navbar-light bg-dark">
          <div class="container">
               <a class="navbar-brand text-white" href="@Url.Action("Index", "Home", new { area = "Admin" })">Admin</a>
               <button class="navbar-toggler navbar-toggler-white" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                       aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon text-light"></span>
               </button>
               <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto">
                         <li class="nav-item">
                              <a class="nav-link text-light" href="@Url.Action("Index", "Users", new { area = "Admin" })">Users</a>
                         </li>
                         <li class="nav-item">
                              <a class="nav-link text-light" href="@Url.Action("Index", "Gyms", new { area = "Admin" })">Scheduled</a>
                         </li>
                         <li class="nav-item">
                              <a class="nav-link text-light" href="@Url.Action("Index", "Products", new { area = "Admin" })">Products</a>
                         </li>
                    </ul>
                    @if (User.Identity.IsAuthenticated)
                    {
                         <ul class="navbar-nav">
                              <li class="nav-item">
                                   <a class="nav-link text-light" href="@Url.Action("Logout", "Home", new { area = "Admin" })">Logout</a>
                              </li>
                         </ul>
                    }
               </div>
          </div>
     </nav>
     <div class="container mt-4">
          @RenderBody()
     </div>
     <footer class="text-center py-3 text-light">
          <p class="m-0">&copy; @DateTime.Now.Year - TI-213</p>
     </footer>

     @Scripts.Render("~/bundles/jquery")
     @Scripts.Render("~/bundles/bootstrap/js")
     @Scripts.Render("~/bundles/jqueryval")
     <!-- Bootstrap JS -->
     <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
     @Scripts.Render("~/bundles/mainScript")
     @RenderSection("scripts", required: false)
</body>
</html>